general:
  app_name: MyLLM
  version: 1.0.0


llm:
  llamacpp:
    base_url: http://localhost:8080/v1

  ollama:
    base_url: http://localhost:11434/v1
    embedding_url: http://localhost:11434

  vllm:
    base_url: http://localhost:8000/v1

  github_models:
    base_url: https://models.inference.ai.azure.com


