[dev]
  functions = "netlify/functions"
  functionsPort = 8888
  targetPort = 8888
  [[redirects]]
      force = true
      from = "/api/*"
      to = "/.netlify/functions/"
      status = 200

# Include all files in all functions
[functions]
  # Sets a custom directory for Netlify Functions
  directory = "netlify/functions/"
  included_files = ["netlify/model/**"]
  [[redirects]]
    from = "/api/*"
    to = "/.netlify/functions/:splat"
    status = 200

