export type ExpansionCandidateCategory = 'animal' | 'vehicle' | 'building';

export type ExpansionCandidateCompliance =
  | 'approved'
  | 'inspiration_only'
  | 'blocked';

export interface ExpansionCandidate {
  id: string;
  name: string;
  category: ExpansionCandidateCategory;
  priority: 1 | 2 | 3;
  sourceLabel: string;
  sourceUrl: string;
  compliance: ExpansionCandidateCompliance;
  plannedTemplateFamily: string;
  whyVoxelizable: string;
  notes: string;
}

export const EXPANSION_CANDIDATES_V1: ExpansionCandidate[] = [
  {
    id: 'candidate-dog-corgi',
    name: '小狗 / 柯基轮廓',
    category: 'animal',
    priority: 1,
    sourceLabel: 'Sketchfab - low-poly dog',
    sourceUrl: 'https://sketchfab.com/3d-models/low-poly-dog-577b6e7656ea41d2885f806c1afce5af',
    compliance: 'approved',
    plannedTemplateFamily: 'dog-family',
    whyVoxelizable: '头身比例清晰，四足+尾巴轮廓明显，适合做 dog / corgi / puppy 变体族。',
    notes: '优先抽象耳朵、腿长、尾巴，不保留原模型表面细节。',
  },
  {
    id: 'candidate-fox',
    name: '狐狸',
    category: 'animal',
    priority: 1,
    sourceLabel: 'Sketchfab - low poly fox',
    sourceUrl: 'https://sketchfab.com/3d-models/low-poly-fox-8372625a70c64a21842a2a524332a6b4',
    compliance: 'approved',
    plannedTemplateFamily: 'fox-family',
    whyVoxelizable: '大尾巴、尖耳和瘦长头部特征适合体素抽象。',
    notes: '可复用于 fox / arctic fox / fantasy fox。',
  },
  {
    id: 'candidate-penguin',
    name: '企鹅',
    category: 'animal',
    priority: 1,
    sourceLabel: 'Sketchfab - low poly penguin',
    sourceUrl: 'https://sketchfab.com/3d-models/low-poly-penguin-8a27f42a0b1646d6b210db9ab668c54f',
    compliance: 'approved',
    plannedTemplateFamily: 'penguin-family',
    whyVoxelizable: '黑白块面对比强，短翅膀和圆肚子容易体素表达。',
    notes: '适合做 emperor penguin / cute penguin / winter mascot。',
  },
  {
    id: 'candidate-turtle',
    name: '海龟 / 乌龟',
    category: 'animal',
    priority: 1,
    sourceLabel: 'Sketchfab - low poly turtle',
    sourceUrl: 'https://sketchfab.com/3d-models/low-poly-turtle-180168bf6f594ddcada436f554feb173',
    compliance: 'approved',
    plannedTemplateFamily: 'turtle-family',
    whyVoxelizable: '龟壳、短腿和低矮姿态适合压缩到中低预算模板。',
    notes: '可扩展到 turtle / sea turtle / fantasy shell creature。',
  },
  {
    id: 'candidate-bird-lovebirds',
    name: '爱情鸟 / 成对小鸟',
    category: 'animal',
    priority: 2,
    sourceLabel: 'LEGO Nature - Love Birds',
    sourceUrl: 'https://www.lego.com/en-us/categories/nature',
    compliance: 'inspiration_only',
    plannedTemplateFamily: 'paired-birds-family',
    whyVoxelizable: '成对主体、鲜明配色和对称结构很适合现有 twins 路线扩展。',
    notes: '仅作为题材与配色参考，不直接继承砖块结构。',
  },
  {
    id: 'candidate-hamster',
    name: '仓鼠',
    category: 'animal',
    priority: 2,
    sourceLabel: 'LEGO Creator 3in1 - Cute Hamster with a Flower',
    sourceUrl: 'https://www.lego.com/en-us/themes/creator-3-in-1',
    compliance: 'inspiration_only',
    plannedTemplateFamily: 'small-pet-family',
    whyVoxelizable: '圆身体、小耳朵和前爪姿态适合小体量模板。',
    notes: '适合扩成 hamster / guinea pig / cute rodent。',
  },
  {
    id: 'candidate-lion-cub',
    name: '小狮子 / 大猫科',
    category: 'animal',
    priority: 3,
    sourceLabel: 'LEGO Animals and Nature - Young Simba',
    sourceUrl: 'https://www.lego.com/en-us/adults-welcome/animals-and-nature',
    compliance: 'inspiration_only',
    plannedTemplateFamily: 'big-cat-family',
    whyVoxelizable: '大头、小身体和尾巴可以沿用现有猫科模板扩展。',
    notes: '适合走 adapt 路线，从 cat-family 演化。',
  },
  {
    id: 'candidate-sedan-car',
    name: '轿车',
    category: 'vehicle',
    priority: 1,
    sourceLabel: 'Sketchfab - Voxel Car Low Poly',
    sourceUrl: 'https://sketchfab.com/3d-models/voxel-car-low-poly-f793fc28c75d4a8d81ba60fe0f62165d',
    compliance: 'blocked',
    plannedTemplateFamily: 'car-family',
    whyVoxelizable: '外形很接近目标体素风格。',
    notes: '该资源标注 NoAI，不建议纳入 AI 辅助模板生成参考链路；已报备并跳过，转用下一个合规来源。',
  },
  {
    id: 'candidate-sedan-car-fallback',
    name: '轿车（替代参考）',
    category: 'vehicle',
    priority: 1,
    sourceLabel: 'Sketchfab - low poly cars',
    sourceUrl: 'https://sketchfab.com/3d-models/low-poly-cars-066f637a93c64a119e96721c628b118f',
    compliance: 'approved',
    plannedTemplateFamily: 'car-family',
    whyVoxelizable: '双车参考提供轿车轮廓、车顶和轮组比例，适合做 sedan / taxi / city car。',
    notes: '用作轿车基础轮廓，不直接照搬贴图与外观细节。',
  },
  {
    id: 'candidate-bus',
    name: '巴士',
    category: 'vehicle',
    priority: 1,
    sourceLabel: 'Sketchfab - low poly bus',
    sourceUrl: 'https://sketchfab.com/3d-models/low-poly-bus-30cf9f7983db48c9a8450ff34c403414',
    compliance: 'approved',
    plannedTemplateFamily: 'bus-family',
    whyVoxelizable: '长矩形车身、车窗带和轮组结构特别适合体素模板。',
    notes: '可扩为 city bus / school bus / shuttle bus。',
  },
  {
    id: 'candidate-fire-truck',
    name: '消防车',
    category: 'vehicle',
    priority: 1,
    sourceLabel: 'Sketchfab - low poly fire truck',
    sourceUrl: 'https://sketchfab.com/3d-models/low-poly-fire-truck-688b7c17a0e54a05b0b2d51a8aee061b',
    compliance: 'approved',
    plannedTemplateFamily: 'emergency-vehicle-family',
    whyVoxelizable: '消防车有非常稳定的识别符号：红色车身、梯子、车头箱体。',
    notes: '适合带动 ambulance / police car 一整组 emergency family。',
  },
  {
    id: 'candidate-train',
    name: '火车头 / 短编组列车',
    category: 'vehicle',
    priority: 2,
    sourceLabel: 'Sketchfab - low poly train',
    sourceUrl: 'https://sketchfab.com/3d-models/low-poly-train-f9620a9de70b4611979db24e48e5fded',
    compliance: 'approved',
    plannedTemplateFamily: 'train-family',
    whyVoxelizable: '车头、车厢、顶部轮廓分层明确，适合低到中预算体素模板。',
    notes: '可和 LEGO trains 类目一起作为题材参考，不照搬任何具体官方造型。',
  },
  {
    id: 'candidate-boat',
    name: '小船',
    category: 'vehicle',
    priority: 2,
    sourceLabel: 'Sketchfab - low poly boat',
    sourceUrl: 'https://sketchfab.com/3d-models/low-poly-boat-78061603535c4119b1a552b35bb6373b',
    compliance: 'approved',
    plannedTemplateFamily: 'boat-family',
    whyVoxelizable: '船体底部和甲板轮廓简单，适合做 boat / fishing boat / rescue boat。',
    notes: '优先做简化体量，不引入复杂桅杆和索具。',
  },
  {
    id: 'candidate-modern-house',
    name: '现代房屋 / 海边屋 / 小木屋',
    category: 'building',
    priority: 1,
    sourceLabel: 'LEGO Creator 3in1 - Modern House',
    sourceUrl: 'https://www.lego.com/en-us/product/modern-house-31153',
    compliance: 'inspiration_only',
    plannedTemplateFamily: 'house-family',
    whyVoxelizable: '同一题材天然分成 modern house / city building / forest cabin 三个变体，适合模板族。',
    notes: '只取屋顶、窗带、体块关系，不取砖块和开合设计。',
  },
  {
    id: 'candidate-low-poly-house',
    name: '基础房屋',
    category: 'building',
    priority: 1,
    sourceLabel: 'Sketchfab - simple low poly house',
    sourceUrl: 'https://sketchfab.com/3d-models/freesimple-low-poly-house-0dfa5257541540a295b8872ece1473b9',
    compliance: 'approved',
    plannedTemplateFamily: 'house-family',
    whyVoxelizable: '整体就是 blocky 低多边形房屋，适合直接转成低预算 voxel house。',
    notes: '可作为 small house 基础，再扩到 cottage / town house。',
  },
  {
    id: 'candidate-tree-house',
    name: '树屋',
    category: 'building',
    priority: 2,
    sourceLabel: 'Sketchfab - low poly tree house',
    sourceUrl: 'https://sketchfab.com/3d-models/low-poly-tree-house-a4a46345a7344dc7b98f5073998769e0',
    compliance: 'approved',
    plannedTemplateFamily: 'treehouse-family',
    whyVoxelizable: '树干+平台+小屋的三段结构很适合体素化和模板分件。',
    notes: '适合 scene / building 混合型模板。',
  },
  {
    id: 'candidate-windmill',
    name: '风车',
    category: 'building',
    priority: 2,
    sourceLabel: 'Sketchfab - low poly windmill',
    sourceUrl: 'https://sketchfab.com/3d-models/low-poly-windmill-7e16ed658d92416e9faae0ad91059e92',
    compliance: 'approved',
    plannedTemplateFamily: 'windmill-family',
    whyVoxelizable: '塔身和扇叶组合非常适合作为识别度高的中型建筑模板。',
    notes: '优先做静态扇叶版本，后续再考虑旋转表现。',
  },
  {
    id: 'candidate-lighthouse',
    name: '灯塔',
    category: 'building',
    priority: 2,
    sourceLabel: 'Sketchfab - free low poly lighthouse',
    sourceUrl: 'https://sketchfab.com/3d-models/free-low-poly-lighthouse-3d-model-88ee8468315a4aa7a2b399d47c7cffd6',
    compliance: 'approved',
    plannedTemplateFamily: 'lighthouse-family',
    whyVoxelizable: '高塔形态清晰，适合作为纵向识别模板。',
    notes: '后续可扩为 coastal scene 相关模板。',
  },
  {
    id: 'candidate-townhouse',
    name: '联排城市建筑',
    category: 'building',
    priority: 3,
    sourceLabel: 'LEGO Creator 3in1 - Modern House city building variant',
    sourceUrl: 'https://www.lego.com/en-us/product/modern-house-31153',
    compliance: 'inspiration_only',
    plannedTemplateFamily: 'town-building-family',
    whyVoxelizable: '三层城市建筑适合与 bus / train / streetcar 形成城市系模板组合。',
    notes: '作为 city scene 的补充模板。',
  },
];
