import type { TemplateRegistryEntry } from '../contracts/index.js';

export const SEED_TEMPLATE_REGISTRY: TemplateRegistryEntry[] = [
  {
    metadata: {
      id: 'seed-eagle-perched',
      name: 'Perched Eagle',
      sourceType: 'generator',
      baseCategory: 'animal',
      subCategory: 'bird_of_prey',
      tags: ['bird', 'eagle', 'perched', 'branch', 'wildlife'],
      styleTags: ['stylized', 'decorative', 'scenic'],
      shapeTags: ['winged', 'tall', 'perched', 'centered'],
      colorTags: ['brown', 'white', 'gold', 'green'],
      complexity: 'medium',
      voxelBudgetRange: { min: 150, max: 220 },
      symmetry: 'soft',
      editableParts: ['head', 'beak', 'wings', 'tail', 'palette', 'branch'],
      promptAliases: ['eagle', 'bird', 'hawk', 'raptor', 'perched bird'],
      negativeKeywords: ['car', 'vehicle', 'castle', 'robot', 'house'],
      rebuildSuitability: 'medium',
      priority: 90,
      status: 'active',
    },
    source: {
      type: 'generator',
      ref: 'src/legacy/utils/voxelGenerators.ts#Generators.Eagle',
    },
  },
  {
    metadata: {
      id: 'seed-cat-seated',
      name: 'Seated Cat',
      sourceType: 'generator',
      baseCategory: 'animal',
      subCategory: 'cat',
      tags: ['cat', 'pet', 'seated', 'cute', 'feline'],
      styleTags: ['cute', 'stylized', 'compact'],
      shapeTags: ['round', 'seated', 'tailed', 'front_facing'],
      colorTags: ['brown', 'white', 'gold', 'black'],
      complexity: 'medium',
      voxelBudgetRange: { min: 140, max: 210 },
      symmetry: 'soft',
      editableParts: ['ears', 'tail', 'face', 'paws', 'palette'],
      promptAliases: ['cat', 'kitty', 'kitten', 'feline', 'cute cat'],
      negativeKeywords: ['car', 'bus', 'castle', 'airplane', 'robot'],
      rebuildSuitability: 'high',
      priority: 95,
      status: 'active',
    },
    source: {
      type: 'generator',
      ref: 'src/legacy/utils/voxelGenerators.ts#Generators.Cat',
    },
  },
  {
    metadata: {
      id: 'seed-rabbit-sitting',
      name: 'Sitting Rabbit',
      sourceType: 'generator',
      baseCategory: 'animal',
      subCategory: 'rabbit',
      tags: ['rabbit', 'bunny', 'cute', 'sitting', 'woodland'],
      styleTags: ['cute', 'soft', 'storybook'],
      shapeTags: ['long_eared', 'round', 'sitting', 'vertical'],
      colorTags: ['white', 'brown', 'green', 'black'],
      complexity: 'medium',
      voxelBudgetRange: { min: 145, max: 210 },
      symmetry: 'soft',
      editableParts: ['ears', 'head', 'tail', 'palette', 'log'],
      promptAliases: ['rabbit', 'bunny', 'hare', 'cute rabbit', 'small bunny'],
      negativeKeywords: ['truck', 'car', 'castle', 'robot', 'dragon'],
      rebuildSuitability: 'high',
      priority: 92,
      status: 'active',
    },
    source: {
      type: 'generator',
      ref: 'src/legacy/utils/voxelGenerators.ts#Generators.Rabbit',
    },
  },
  {
    metadata: {
      id: 'seed-twins-birds',
      name: 'Twin Birds',
      sourceType: 'generator',
      baseCategory: 'animal',
      subCategory: 'paired_birds',
      tags: ['birds', 'twins', 'pair', 'double', 'companion'],
      styleTags: ['stylized', 'paired', 'decorative'],
      shapeTags: ['paired', 'wide', 'mirrored', 'two_subjects'],
      colorTags: ['brown', 'white', 'gold', 'green'],
      complexity: 'medium',
      voxelBudgetRange: { min: 140, max: 200 },
      symmetry: 'strong',
      editableParts: ['pairing', 'heads', 'wings', 'palette', 'branch'],
      promptAliases: ['twins', 'two birds', 'double birds', 'pair of birds', 'two eagles'],
      negativeKeywords: ['single car', 'castle', 'robot', 'house'],
      rebuildSuitability: 'medium',
      priority: 88,
      status: 'active',
    },
    source: {
      type: 'generator',
      ref: 'src/legacy/utils/voxelGenerators.ts#Generators.Twins',
    },
  },
];
